# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd src
    - yarn
  artifacts:
    paths:
      - node_modules/
    
test:
  stage: test
  script: 
    - cd src
    - yarn test

deploy_prod:
  stage: deploy
  script:
    - pm2 delete japanese-api-prod; true
    - rsync --verbose --recursive --delete src /home/japanese-api/prod
    - pm2 start /home/japanese-api/prod/index.js --name japanese-api-prod
  environment:
    name: production
    url: https://www.iccan.us/japanese-api
  when: manual
  only:
  - master