# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - build/

stages:
  - build_application
  - build_database
  - test
  - deploy

build_application:
  stage: build_application
  script: 
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - build/

build_database:
  stage: build_database
  script:
    - yarn build-db
    
test:
  stage: test
  script: 
    - yarn test

deploy_prod:
  stage: deploy
  script:
    - pm2 delete japanese-api-prod || true
    - rsync --verbose --recursive --delete . /home/japanese-api/prod
    - pm2 start /home/japanese-api/prod/build/index.js --name japanese-api-prod # TODO: restart when crashing?
  environment:
    name: production
    url: https://www.iccan.us/japanese-api
  # when: manual
  only:
  - master